// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABEPlZCiDJVHR1Q4BwPKPt9ZhIk3gzOZg',
    appId: '1:1085115730295:web:e4d3f63c405e1fed64f972',
    messagingSenderId: '1085115730295',
    projectId: 'blooddonation-184b1',
    authDomain: 'blooddonation-184b1.firebaseapp.com',
    storageBucket: 'blooddonation-184b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV2QGswWTCOy7i0Aw0ZvyjTdOmcnGSX4A',
    appId: '1:1085115730295:android:c574df911b2e41e964f972',
    messagingSenderId: '1085115730295',
    projectId: 'blooddonation-184b1',
    storageBucket: 'blooddonation-184b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7eRe31yTMUu43ViRRqAKPxZSjOS_eEAc',
    appId: '1:1085115730295:ios:c057c0890f02db2664f972',
    messagingSenderId: '1085115730295',
    projectId: 'blooddonation-184b1',
    storageBucket: 'blooddonation-184b1.appspot.com',
    iosBundleId: 'com.example.flutterBlooddonation19',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7eRe31yTMUu43ViRRqAKPxZSjOS_eEAc',
    appId: '1:1085115730295:ios:c057c0890f02db2664f972',
    messagingSenderId: '1085115730295',
    projectId: 'blooddonation-184b1',
    storageBucket: 'blooddonation-184b1.appspot.com',
    iosBundleId: 'com.example.flutterBlooddonation19',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABEPlZCiDJVHR1Q4BwPKPt9ZhIk3gzOZg',
    appId: '1:1085115730295:web:7f4f399ed9cd130f64f972',
    messagingSenderId: '1085115730295',
    projectId: 'blooddonation-184b1',
    authDomain: 'blooddonation-184b1.firebaseapp.com',
    storageBucket: 'blooddonation-184b1.appspot.com',
  );
}
